import { NextResponse } from 'next/server';

export async function middleware(request) {
  // 1. Get the data the user is trying to send to your website
  // We check the URL parameters (e.g., website.com/search?q=<script>alert(1)</script>)
  let payloadToCheck = request.nextUrl.search; 

  // If the user is submitting a form (POST request), we also grab the body text
  if (request.method === 'POST') {
    try {
      const clonedReq = request.clone();
      const bodyText = await clonedReq.text();
      payloadToCheck += " " + bodyText;
    } catch (e) {
      console.error("Could not read request body", e);
    }
  }

  // If there's no input to check, just let them into the website normally
  if (!payloadToCheck || payloadToCheck.trim() === '') {
    return NextResponse.next();
  }

  // 2. Send the data to your Render WAF Brain
  try {
    const wafResponse = await fetch('https://firewall-1-jajw.onrender.com/api/waf', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ payload: payloadToCheck })
    });

    const wafData = await wafResponse.json();

    // 3. THE SHIELD: Block or Allow based on the ML Model's decision
    if (wafData.block === true) {
      // The model detected an attack! 
      // We block the user and show them the exact explanation generated by your LIME explainer.
      return new NextResponse(
        JSON.stringify({
          status: "Blocked by AI Firewall",
          attack_type: wafData.attack_type,
          confidence: wafData.confidence,
          explanation: wafData.explanation
        }),
        { 
          status: 403, // 403 Forbidden
          headers: { 'content-type': 'application/json' } 
        }
      );
    }
  } catch (error) {
    // If Render goes offline, this "fails open" so your site doesn't crash.
    console.error("WAF API is unreachable:", error);
  }

  // 4. If it's safe (block === false), let the user see the website!
  return NextResponse.next();
}

// 5. Configuration: Tell Vercel which pages to protect
export const config = {
  matcher: [
    /*
     * Match all request paths EXCEPT for static files and images.
     * We don't need to run ML models on requests for your website's logo or CSS.
     */
    '/((?!_next/static|_next/image|favicon.ico).*)',
  ],
}